import { FC } from 'react'
import Head from 'next/head'
import Link from 'next/link'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="indexWrapper">
        <h1 className="indexTitle">Styling with...</h1>
        <div className="indexLinks">
          <Link href="/css-modules">
            <a className="indexLink">CSS Modules</a>
          </Link>
          <Link href="/styled-jsx">
            <a className="indexLink">styled-jsx</a>
          </Link>
        </div>
      </div>
    </>
  )
}

export default Home
