import { FC } from 'react'
import Head from 'next/head'

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Index Page</h1>
    </>
  )
}

export default Home
